# Generated by Django 4.0.3 on 2023-07-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_alter_sale_automobile_alter_salesperson_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='sold',
            field=models.BooleanField(),
        ),
    ]
